### ISSUE TITLE
usage question: how to actually trigger a hipchat notification using notify() or the Notification facade?

### ISSUE THREAD

**Issue by larsbo** [laravel-notification-channels/hipchat#13]
I experimented a bit with this package and also read the notifcation documentation at https://laravel.com/docs/master/notifications but I'm still unsure how to trigger a HipChat notifcation in my code.

At the Laravel documentation there is a Facade example for an email notification:

``` php
Notification::send($users, new InvoicePaid($invoice));
```

How an equivalent HipChat notification would look? Should `$users` are an array of HipChat rooms?

**Comment by pmatseykanets** [comment]
The example from the Laravel documentation, which you showed, is absolutely driver (channel) agnostic therefore HipChat notification will be indistinguishable from Mail, Slack or Database ones. More over you can use all these and more channels simultaneously.

Now it all really depends on how your hipchat is set up is being used by users and the application specific notification routing logic. Are all of the users are members of the same hipchat room and expect InvoicePaid notifications in there, which probably makes sense, or every user has their own room?

If it's the former than passing the collection of users to `Notification::send()` probably doesn't make whole lot of sense just because the same message will be repeated in the room for each user in that collection. You can do this instead 

``` php
(new User())->notify(new InvoicePaid($invoice));
Notification::send([new User()], new InvoicePaid($invoice));
```

You can also "mention" all relevant users in your room notification if you store users' hipchat ids (handles) by optionally passing the user collection to the `InvoicePaid` notification itself.

``` php
(new User())->notify(new InvoicePaid($invoice, $users));
```

``` php
class InvoicePaid extends Notification
{
    // ...
    protected $invoice;
    protected $users;

    public function __construct($invoice, Collection $users = null)
    {
        $this->invoice = $invoice;
        $this->users = $users ?: Collection::make();
    }

    public function toHipChat($notifiable)
    {
        $mentions = $this->users->map(function ($user) {
            return "@$user->hipchat";
        })->implode(' ');

        return HipChatMessage::create()
            ->text($mentions."Invoice {$this->invoice->id} has been paid.");
    }
    // ...
}
```

_Note_ that any object not only `User` can be `Notifiable` . Meaning if you have some sort of group in your application and all users that watch for invoice notifications belong to that group you can do

``` php
$group->notify(new InvoicePaid($invoice, $users));
```

Even `Invoice` model itself can be notifiable if it makes more sense to route notifications this way and can return a proper room identifier

``` php
$invoice->notify(new InvoicePaid($invoice, $users));
```

``` php

class Invoice extends Model
{
    use Notifiable;

    public function routeNotificationForHipChat()
    {
        return 'InvoiceRoom';
    }
}
```

Hope this helps.

**Comment by larsbo** [comment]
@pmatseykanets Thank you very much for the detailed explanation and examples! :+1: 
That helps a lot and makes the use much clearer. I didn't know that the notifiation concept and this package can be used in so many different ways.

As you have guessed right, I want to send a single notification to a room with multiple users. 
This variant looks promising:

``` php
Notification::send([new User()], new InvoicePaid($invoice));
```

And the other examples are very interesting, too. Maybe I can use some for other tasks :)

**Comment by pmatseykanets** [comment]
No worries. Don't hesitate to ask any follow up questions if needed. :)
